name: ci

on:
  push:
    pull_request:
      branches:
        - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: 'npm'

      - name: Install dependencies
        run: npm run ci:all

      - name: Lint
        working-directory: ./api
        run: npm run lint

      - name: Tests
        working-directory: ./api
        run: npm test
