name: cd

on:
  push:
    branches:
      - main
  #schedule:
  # - cron: '10 9 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm run ci:all

      - name: Get WOD
        working-directory: ./api
        run: npm run get-wod

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY/MM/DD

      - name: Commit WOD
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add new wod ${{ steps.current-time.outputs.formattedTime }}

      - name: Generate website
        run: (cd api && npm start &); cd webapp && npm run generate
        env:
          API_URL: http://localhost:3000
          ANALYTICS_ENABLED: ${{ secrets.ANALYTICS_ENABLED }}
          ANALYTICS_URL: ${{ secrets.ANALYTICS_URL }}
          ANALYTICS_DOMAIN_URL: ${{ secrets.ANALYTICS_DOMAIN_URL }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webapp/dist
          cname: wods.vincenthardouin.dev
